title: "Appunti di Letteratura Italiana"
author: "Lumi"
description: "Raccolta di appunti utili per la maturità"
theme: jekyll-theme-cayman # Un bellissimo tema integrato nativamente nelle GitHub Pages
