title: "Appunti Maturità 2026"
author: "Lumi"
description: "Raccolta di appunti per la maturità dal design minimale."

# Disabilitiamo esplicitamente i temi di GitHub Pages per usare il nostro CSS custom
theme: null
